---
version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    image: ${USERNAME}/ui
    ports:
      - ${UI_PORTS}:${UI_PORTS}/tcp
    networks:
      - reddit
  post:
    image: ${USERNAME}/post
    networks:
      - reddit
  comment:
    image: ${USERNAME}/comment
    networks:
      - reddit

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - reddit

networks:
  reddit:

volumes:
  post_db:
  prometheus_data:
