---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-dynamic
spec:
  storageClassName: "yc-network-nvme"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
