---

apiVersion: v1
kind: Secret
metadata:
  name: ui-ingress
type: kubernetes.io/tls
data:
  tls.crt: -----BEGIN CERTIFICATE-----
MIIDDzCCAfegAwIBAgIUP7oGRJ0UlSS3AAKTgpyBL0aowU4wDQYJKoZIhvcNAQEL
BQAwFzEVMBMGA1UEAwwMNTEuMjUwLjkuMTMyMB4XDTIyMDEyODA4NTcxOVoXDTIz
MDEyODA4NTcxOVowFzEVMBMGA1UEAwwMNTEuMjUwLjkuMTMyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsI8CFTZUURRlc9J5br1/0Gf49K7Qrf62KWjM
oCPJON/gcsKM+zPgo8mDZMiD0PLnTFlYRJ7dPD6wWsJ2lFLKwLJSlNO9KJMFYJ3u
hVdRMnL3xEqkniC94oBkbA/6expg9m0Hjc2IIfXDDeDX/QhB4i7UBaoPgYIbuVJ7
z4CRfoNFd7MyPR7DBOZohe7dSCYlxvY8lk8uZsMw1XWp8W0UFeoytf6twIbSx91Q
PBk7Z3UpPz/j8VRWPh3WUj1cGDTiROTSzmvFcUUbaFdTyzvSovJ4DGS82X6d0P5S
dZE16t4g5fXWzxRqUQLS1LxXSMlV8T5VXDLlFTxOJsJcPX8JswIDAQABo1MwUTAd
BgNVHQ4EFgQU0bXKLiENQg/wDKRYmKt4XRap6UAwHwYDVR0jBBgwFoAU0bXKLiEN
Qg/wDKRYmKt4XRap6UAwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
AQEACEPemYo3Mh9egd6PrxQbr1cfvr99NnPLRu2rrZBaYxbccOAI2yMumSYA9/pl
t9veeO9xP8MOpS6dIrJfhLoanCTd34Fv7zTG04s46o7Bea9h2uQZrvZltdsP54s2
yh4dQjrE5f2sMN2/77B+vsL821mzPnP7LIQ85/2oTjGbVQYCkF3lxLkXLxw5DBc1
WEQfjtyUBI5nob5iKeuoLruIvP+6XXc7bqOk9bh4U7ivB2sAbPhMtOoNpd29L1w+
PGf7Z1Rbw0r74t6+jE0mG+YVzVAFG6Hb1U239oTLDhvQS6WnkbnDoCSPOCNkI5Nc
IfVea7VkNtz0r6WVPW1/EhKH1A==
-----END CERTIFICATE-----
  tls.key: -----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwjwIVNlRRFGVz
0nluvX/QZ/j0rtCt/rYpaMygI8k43+Bywoz7M+CjyYNkyIPQ8udMWVhEnt08PrBa
wnaUUsrAslKU070okwVgne6FV1EycvfESqSeIL3igGRsD/p7GmD2bQeNzYgh9cMN
4Nf9CEHiLtQFqg+Bghu5UnvPgJF+g0V3szI9HsME5miF7t1IJiXG9jyWTy5mwzDV
danxbRQV6jK1/q3AhtLH3VA8GTtndSk/P+PxVFY+HdZSPVwYNOJE5NLOa8VxRRto
V1PLO9Ki8ngMZLzZfp3Q/lJ1kTXq3iDl9dbPFGpRAtLUvFdIyVXxPlVcMuUVPE4m
wlw9fwmzAgMBAAECggEAByLwqZzVkaVqaGEUiXZdaTYaqQE77ByEjm3u/3YS1xqt
ftYATtMM/HHTvsogEd0PnlVqLPPi62F5TWHY2yvxiBJtJhjc53vx1rLrhjY+UPS2
sRd3SfD22+XmqTuIG1u4mZ1UldW97+l4JeJ1uIOR7iuIZGY4VDrHFhmQaZW/y8Y/
XUeV1qe8ZgT0bLKLOkZntsqt0Vd1PiBybZqAzTC0JAO4iQQR53e3Lw8bUnxdFULq
gn3U3OMgW6WdEAJ4HgcA92uvPbi6OwH9aYEj5u2NUtU4nzxul6FoIidGm9ddELHu
YaRehtowODWCzL2Xv12LU2Bb8hP8oHMAczID/BGJmQKBgQDgcPwC9cYBwt0FZoSE
cEY7mrodQN+o1JYbbqJbI8clJ9rcyAX8fycgljKYzXQMCgf1Ss+lmfGeEDBA9BT3
XvA1VsDDK7MzdwmcXadHsrkjLYfUAr17TGz4QJmQZgd3dw8N8d3Y7R2C7UR6BpN9
dzUnmHPq0ZIgJ4SLdNFN4+FRVwKBgQDJYm6YsKEJYA7BkudPY9hguzl0R0yswBw2
7lJZwNfEiDbnsEGp29d3jh+dSDZ6GqXz8Io0m51bO8AYD9Pq6LT42TQi0+n1QKlu
qWoKWYFnniVnA3aQ4vtxOj9hmjgwSfbJKV3Yp58NCnlYTDy2KZcDcjzOnllhcZIt
XeqQUrRFBQKBgEhIuzFs3Gemza42lUleK5B4xaY0RZRHW0zcddeqjzHNQzTGCv+G
KCDbntINoWlbNbLvdC7ehK2mgxP4SGRfJDfZh92TznQty1+b3gs+aVgGCu/iLgpu
082kaJDT+2WjZ6rTEeMSguWu6tXuFkRbRzhIZlTjSA+pCowrhFl0ohWjAoGAbvjw
3O8oLlRijUT4dgUdLWC+blcD54YNhi+Z7Z+YxtIQ/2dfJ8zfVSBaR3+NlYetv1jj
r824zpeEaT3/l0kYwLBgTHjeSamSNErjBkUATCsXjUaZRYnu6Rwh5RTotaNsfLlw
33yu5q7I42FPa0pLzzhaTblwo4PD+3/vTAxnDkkCgYEAqVG9XhxQU8mLVv3HfM0U
jbPHKlzLXkr7vzCQDbQehbj5gQ1MborEQUm2w7gvmlCytCTxiVRjMFKhbA+UVK6s
JFtuazNfGHQbKcm4yfWAGyKMSWsqn4gYFoS+VuglYuXyjyy+vkyICkbacngLjfgU
LhWOhrHvyd3gqX0v6raQhKM=
-----END PRIVATE KEY-----

