version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${IMG_VER}
    ports:
      - ${UI_PORTS}:${UI_PORTS}/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${IMG_VER}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${IMG_VER}
    networks:
      - reddit

volumes:
  post_db:

networks:
  reddit:
